### ISSUE TITLE
Strange Behaviour of Facets

### ISSUE THREAD

**Issue by FabiApfelkern** [policycompass/policycompass-frontend#295]
I'm not sure if it is a bug, but I think it is strange. Browsing to https://alpha.policycompass.eu/app/#!/browse: 
- Filtering by the first Policy Domain (Gov....)
- 5 Policy Domains are left
- Adding another one (Pop...)
- Now 7 Policy Domains are there

I always thought it should be becoming less and not more, when filtering more.

**Comment by cbotsikas** [comment]
It's because the selected facets from the same category are handled with OR operators, resulting to more results and thus the facet options and counters (may) increase:
![image](https://cloud.githubusercontent.com/assets/1640100/12458017/d811bd6e-bfa7-11e5-951c-4a3adb91a7ee.png)

If i change the query to use AND operators instead, it's reducing the amount of the results and thus the facet options:
![image](https://cloud.githubusercontent.com/assets/1640100/12457990/b6e3718c-bfa7-11e5-8bad-321554f2cc96.png)

Just for comparison, these are the results with only one of the facets selected:
![image](https://cloud.githubusercontent.com/assets/1640100/12458084/31ee3d08-bfa8-11e5-9d94-da86e8926b36.png)

**Comment by FabiApfelkern** [comment]
Sorry for putting this into the wrong issue system. It happened not on purpose. :)
In my opinion a classic facet search works with AND, isn't it? As I want to narrow down my results. 
@YuriGlickman What do you think?

**Comment by YuriGlickman** [comment]
Personally, I think for the location facet and for domain facets should have diferent behavior compare to the content type facet. It should be possible to select several option at the same time (for example, Greece and Germany).

**Comment by cbotsikas** [comment]
This issue has been resolved by changing the query behavior (https://github.com/policycompass/policycompass/issues/443).
